CREATE DATABASE coffeeDB;

USE coffeeDB;

CREATE TABLE coffee (
	id INT NOT NULL AUTO_INCREMENT,
    brand VARCHAR(100) NOT NULL,
    bean_name VARCHAR (100) NOT NULL,
    roast VARCHAR (20) NULL,
    profile1 VARCHAR (100) NULL,
    profile2 VARCHAR (100) NULL,
    profile3 VARCHAR (100) NULL,
    profile4 VARCHAR (100) NULL,
    origin1 VARCHAR (100) NULL,
    origin2 VARCHAR (100) NULL,
    origin3 VARCHAR (100) NULL,
    decaf BOOLEAN,
    PRIMARY KEY (id)    
);

INSERT INTO coffee (brand, bean_name, roast, profile1, profile2, profile3, profile4, origin1, origin2, origin3, decaf)
VALUES ("Rimini", "Canyon", "Light", "earthy", "nutty", "spicy", "herbal", "Central America", "South America", "Africa", 0),
("Rimini", "Baldoria", "Light", "fruity", "full-bodied", "caramel", NULL, NULL, "South America", "Indonesia", NULL, 0),
("Rimini", "Fair Trade Organic Vienna", "Dark", "cocoa", "full-bodied", "floral", NULL, "South America", "Central America", "Africa", 0),
("Rimini", "Fair Trade Organic Espresso", "Dark", "nutty", "caramel", "full-bodied", NULL, "South America", "Central America", "Indonesia", 0),
("Rimini", "Magnificent 7", "Light", "dark chocolate", "caramel", "berry", NULL, "South America", "Africa", "Indonesia", 0),
("Rimini", "Fair Trade Organic French Roast", "Dark", "rich", "smoky", "spicy", "citrus", "South America", "Africa", "Indonesia", 0),
("Rimini", "Milano", "Medium", "floral", "chocolate", "nougat", "raisin", "South America", "Central America", "Africa", 0),
("Rimini", "Pastore", "Dark", "smoky", "nutty", "cocoa", "floral", "South America", "Africa", "Indonesia", 0),
("Rimini", "Perugia Espresso", "Dark", "cocoa", "nutty", "sweet", "citrus", "South America", "Central America", "Africa", 0),
("Rimini", "Raccolto Grande", "Dark", "smoky", "nutty", "spicy", "full-bodied", "South America", "Indonesia", "Africa", 0),
("Rimini", "Stelalto", "Light", "maple", "toffee", "chocolate", "raspberry", "Central America", "south America", "Africa", 0),
("Rimini", "Swiss Water Decaf Giardinia", "Light", "smooth", "medium-bodied", "nutty", "cocoa", NULL, NULL, NULL, 1),
("Rimini", "Organic Colombia", "Light", "raspberry", "toffee", NULL, NULL, "Colombia", "South America", NULL, 0),
("Rimini", "Costa Rica", "Light", "chocolate", "toffee", NULL, NULL, "Costa Rica", "Central America", NULL, 0),
("Rimini", "Ethiopia Kaffa", "Light", "blackberry", "cola", "lemon lime", "nectarine", "Ethiopia", "Africa", NULL, 0),
("Rimini", "Ethiopia Limmu", "Light", "blueberry", "strawberry", "cherry", "chocolate", "Ethiopia", "Africa", NULL, 0),
("Rimini", "Ethiopia Yirgacheffe", "Light", "apricot", "lemon lime", NULL, NULL, "Ethiopia", "Africa", NULL, 0),
("Rimini", "Fair Trade Organic Guatemala", "Light", "chocolate", "citrus", NULL, NULL, "Guatemala", "Central America", NULL, 0),
("Rimini", "Kenya", "Light", "wine", "citrus", NULL, NULL, "Kenya", "Africa", NULL, 0),
("Rimini", "Mexican Organic", "Light", "sweet", "citrus", "cocoa", "medium-bodied", "Mexico", "Central America", NULL, 0),
("Rimini", "Peru Amazonas", "Light", "apple", "cherry", "grape", "dark chocolate", "Peru", "South America", NULL, 0),
("Rimini", "Rwanda", "Light", "caramel", "apricot", "chocolate", "melon", "Rwanda", "Africa", NULL, 0),
("Rimini", "Sulawesi", "Medium", "dark chocolate", "black cherry", NULL, NULL, "Sulawesi", "Indonesia", NULL, 0),
("Rimini", "Sulawesi Rantemario", "Light", "green apple", "citrus", "earthy", NULL, "Sulawesi", "Indonesia", NULL, 0),
("Rimini", "Sumatra", "Medium", "spicy", "herbal", NULL, NULL, "Sumatra", "Indonesia", NULL, 0),
("Rimini", "Zambia", "Light", "watermelon", "apricot", "lime", NULL, "Zambia", "Africa", NULL, 0);

INSERT INTO coffee (brand, bean_name, roast, profile1, profile2, profile3, profile4, origin1, origin2, origin3, decaf)
VALUES ("Publik", "Miles Goodyear's Cabin", NULL, "chocolate", "brown sugar", "nutty", "citrus", NULL, NULL, NULL, 0),
("Publik", "Central Ninth Espresso", "Dark", "caramel", "dark chocolate", "fruity", "vanilla", "Central America", "Ethiopia", "Africa", 0),
("Publik", "Beekeeper", "Light", NULL, NULL, NULL, NULL, "Brazil", "Myanmar", "Indonesia", 0),
("Publik", "Swiss Water Sumatra Decaf", "Light", "full-bodied", NULL, NULL, NULL, "Sumatra", "Indonesia", NULL, 1);

INSERT INTO coffee (brand, bean_name, roast, profile1, profile2, profile3, profile4, origin1, origin2, origin3, decaf)
VALUES ("Caffe Ibis", "Arianto", "Light", "juicy", "black cherry", "herbal", NULL, "Sumatra", "Indonesia", NULL, 0),
("Caffe Ibis", "Aztec Dark", "Dark", "dark chocolate", "citrus", "caramel", NULL, "Honduras", "Central America", NULL, 0),
("Caffe Ibis", "Organic Bena Bena Valley", "Medium", "spicy", "floral", "chocolate", NULL, "Papua New Guinea", "Indonesia", NULL, 0),
("Caffe Ibis", "Organic Café Femenino", "Dark", "graham cracker", "sugar", "dark chocolate", NULL, "Peru", "South America", NULL, 0),
("Caffe Ibis", "Organic Chapada", "Medium", "nutty", "cookie", "honey", NULL, "Brazil", "South America", NULL, 0),
("Caffe Ibis", "Organic Colombia Huila", "Medium", "fruity", "spicy", "caramel", NULL, "Colombia", "South America", NULL, 0),
("Caffe Ibis", "Organic COMSA", "Medium", "nougat", "vanilla", "dark chocolate", NULL, "Honduras", "Central America", NULL, 0),
("Caffe Ibis", "Organic Dark Colombian Huila", "Dark", "toasted spice", "graham cracker", "molasses", NULL, "Colombia", "Central America", NULL, 0),
("Caffe Ibis", "Organic Ethiopian Arabian Night", "Dark", "berry", "candy", "chocolate", NULL, "Ethiopia", "Africa", NULL, 0),
("Caffe Ibis", "Organic Ethiopian Worka", "Light", "juicy", "floral", "berry", NULL, "Ethiopia", "Africa", NULL, 0),
("Caffe Ibis", "Organic Guatemalan Dark", "Dark", "earthy", "grilled vegetables", "chocolate", "cookie", "Guatemala", "Central America", NULL, 0),
("Caffe Ibis", "Organic Guatemalan Forest", "Medium", "caramel", "fruity", "chocolate", NULL, "Guatemala", "Central America", NULL, 0),
("Caffe Ibis", "Organic Honduran Copán", "Light", "almond", "assam tea", "honey", NULL, "Honduras", "Central America", NULL, 0),
("Caffe Ibis", "Organic Ixil", "Medium", "marzipan", "chocolate", "sweet", NULL, "Guatemala", "Central America", NULL, 0),
("Caffe Ibis", "Organic Ixil Dark", "Dark", "caramel", "spicy", "smokey", NULL, "Guatemala", "Central America", NULL, 0),
("Caffe Ibis", "Organic Kokowagayo", "Medium", "sweet", "rustic", "chamomile", "chocolate syrup", "Sumatra", "Indonesia", NULL, 0),
("Caffe Ibis", "Organic Kokowagayo Dark", "Dark", "earthy", "black pepper", "honey", "raisin", "Sumatra", "Indonesia", NULL, 0),
("Caffe Ibis", "Organic Mexican Chiapas", "Medium", "citrus", "chocolate", "honey", NULL, "Mexico", "Central America", NULL, 0),
("Caffe Ibis", "Organic Peruvian Andes", "Medium", "floral", "milk chocolate", "honey", NULL, "Peru", "South America", NULL, 0),
("Caffe Ibis", "Organic Peruvian Rainforest", "Medium", "floral", "citrus", "dark chocolate", NULL, "Peru", "South America", NULL, 0),
("Caffe Ibis", "Organic Sipi Falls", "Medium", "honey", "apricot", "chocolate", NULL, "Uganda", "Africa", NULL, 0),
("Caffe Ibis", "Organic ANCA Nature's Delight", "Medium Dark", "chocolate", "toasted marshmallow", "molasses", NULL, "Central America", NULL, NULL, 0),
("Caffe Ibis", "Organic Dark Side of the Moon", "Extra Dark", "smoky", "caramel", "burnt sugar", NULL, "Central America", "Africa", NULL, 0),
("Caffe Ibis", "Organic Double French", "Extra Dark", "smoky", "caramel", "burnt sugar", NULL, "Central America", NULL, NULL, 0),
("Caffe Ibis", "Organic Espresso Roast", "Dark", "graham cracker", "caramel", "syrup", NULL, "Central America", NULL, NULL, 0),
("Caffe Ibis", "Organic French Roast", "Dark", "molasses", "chocolate", "graham cracker", NULL, "Central America", NULL, NULL, 0),
("Caffe Ibis", "Organic Ibis Signature Blend", "Medium Dark", "cherry", "strawberry", "caramel", "chocolate", "Indonesia", "Central America", NULL, 0),
("Caffe Ibis", "Organic Light Side of the Moon", "Medium", "dried mango", "cocoa", "honey", "sweet", "Africa", "Central America", NULL, 0),
("Caffe Ibis", "Organic Logan Canyon Blend", "Medium Dark", "spicy", "earthy", "chocolate", "citrus", "Central America", "Indonesia", NULL, 0),
("Caffe Ibis", "Organic Mayan Sunrise Blend", "Medium Dark", "nutty", "caramel", "dark chocolate", NULL, "Central America", NULL, NULL, 0),
("Caffe Ibis", "Organic Mayan Trail Blend", "Medium Dark", "cola", "sweet", "chocolate", "smoky", "Central America", NULL, NULL, 0),
("Caffe Ibis", "Organic Moab Trail Blend", "Medium Dark", "brown sugar", "orange", "citrus", "cocoa", "Central America", NULL, NULL, 0),
("Caffe Ibis", "Organic Moonshot Espresso", "Dark", "molasses", "chocolate", "graham cracker", NULL, "Central America", "Africa", NULL, 0),
("Caffe Ibis", "Organic Sedona Sunrise Blend", "Medium Dark", "caramel", "smoky", "roasted vegetables", NULL, "Indonesia", "Peru", "South America", 0),
("Caffe Ibis", "Organic Vienna Roast", "Extra Dark", "nutty", "black pepper", "molasses", NULL, "Central America", NULL, NULL, 0);

INSERT INTO coffee (brand, bean_name, roast, profile1, profile2, profile3, profile4, origin1, origin2, origin3, decaf)
VALUES ("Salt Lake Roasting Co", "A.M. Blend", "Light", NULL, NULL, NULL, NULL, "Central America", "South America", NULL, 0),
("Salt Lake Roasting Co", "African Queen", "Light", "sweet", "fragrant", NULL, NULL, "Africa", NULL, NULL, 0),
("Salt Lake Roasting Co", "Alpenglow Blend (Organic & Fair Trade)", "Medium", "full-bodied", NULL, NULL, NULL, "Africa", "South America", "Central America", 0),
("Salt Lake Roasting Co", "Brazil", "Medium", "earthy", "Sweet", "full-bodied", NULL, "Brazil", "South America", NULL, 0),
("Salt Lake Roasting Co", "Brazil Organic", "Light", "fruity", "cocoa", "caramel", "apple", "Brazil", "South America", NULL, 0),
("Salt Lake Roasting Co", "Celebes Kolassie / Sulawesi", "Medium", "full-bodied", NULL, NULL, NULL, "Indonesia", "Sulawesi", NULL, 0),
("Salt Lake Roasting Co", "Colombia", "Light", "bright", NULL, NULL, NULL, "Colombia", "South America", NULL, 0),
("Salt Lake Roasting Co", "Colombia Fair Trade Organic Cauca Amucc Ecotact", "Light", "lemon", "cherry", "apple", "caramel", "Colombia", "South America", NULL, 0),
("Salt Lake Roasting Co", "Colombia Natural Decaf", "Medium", "floral", "rich", NULL, NULL, "Colombia", "South America", NULL, 1),
("Salt Lake Roasting Co", "Costa Rica", "Medium", "tart", "full-bodied", NULL, NULL, "Costa Rica", "Central America", NULL, 0),
("Salt Lake Roasting Co", "Costa Rica - La Amistad Organic", "Light", "maple", "sweet", "cherry", "butter", "Costa Rica", "Central America", NULL, 0),
("Salt Lake Roasting Co", "El Salvador Honey  Pacamara - Finca Leticia", "Light", "chocolate", "malt", "honey", "fruity", "El Salvador", "Central America", NULL, 0),
("Salt Lake Roasting Co", "Espresso", "Dark", "full-bodied", "oily", NULL, NULL, NULL, NULL, NULL, 0),
("Salt Lake Roasting Co", "Espresso Decaf KVW", "Dark", "dark", "oily", NULL, NULL, NULL, NULL, NULL, 1),
("Salt Lake Roasting Co", "Espresso Organic (Formerly Viennese)", "Extra Dark", "dark", NULL, NULL, NULL, NULL, NULL, NULL, 0),
("Salt Lake Roasting Co", "Ethiopia (Mocca) Decaf Fair Trade Organic", "Light", "unique", "wine", NULL, NULL, "Ethiopia", "Africa", NULL, 1),
("Salt Lake Roasting Co", "Ethiopia Longberry Harrar", "Light", "wine", "unique", NULL, NULL, "Ethiopia", "Africa", NULL, 0),
("Salt Lake Roasting Co", "Ethiopia Natural Yirgacheffe (Organic)", "Light", "fruity", "full-bodied", NULL, NULL, "Ethiopia", "Africa", NULL, 0),
("Salt Lake Roasting Co", "Ethiopia Yirgacheffe", "Light", "sweet", "bright", "delicate", NULL, "Ethiopia", "Africa", NULL, 0),
("Salt Lake Roasting Co", "Far East Rim", "Dark", "earthy", "full-bodied", "dark", NULL, NULL, NULL, NULL, 0),
("Salt Lake Roasting Co", "French Roast", "Dark", "caramel", "dark", NULL, NULL, NULL, NULL, NULL, 0),
("Salt Lake Roasting Co", "Guatemala Antigua Bella Carmona", "Medium", "full-bodied", "crisp", "spicy", NULL, "Guatemala", "Central America", NULL, 0),
("Salt Lake Roasting Co", "Guatemala Organic", "Medium", "wine", "complex", NULL, NULL, "Guatemala", "Central America", NULL, 0),
("Salt Lake Roasting Co", "Hawaiian Sunrise", "Light", "kona", "delicate", "sweet", NULL, "Hawaii", NULL, NULL, 0),
("Salt Lake Roasting Co", "Honduras Fair Trade ORganic", "Medium", "acidic", NULL, NULL, NULL, "Honduras", "Central America", NULL, 0),
("Salt Lake Roasting Co", "House Blend", "Medium", "rich", "full-bodied", NULL, NULL, "Central America", "Indonesia", "Africa", 0),
("Salt Lake Roasting Co", "House Blend Decaf", "Medium", "rich", "full-bodied", NULL, NULL, "Central America", "Indonesia", "Africa", 1),
("Salt Lake Roasting Co", "India Monsoon Malabar", "Dark", "earthy", "dark", "musty", NULL, "India", NULL, NULL, 0),
("Salt Lake Roasting Co", "Jamaica Blue Mountain", "Dark", NULL, NULL, NULL, NULL, "Jamaica", NULL, NULL, 0),
("Salt Lake Roasting Co", "Jamaica Sunrise", "Dark", NULL, NULL, NULL, NULL, "Jamaica", NULL, NULL, 0),
("Salt Lake Roasting Co", "Java", "Medium", "full-bodied", "thick", "smooth", NULL, "Indonesia", "Java", NULL, 0),
("Salt Lake Roasting Co", "Kenya", "Dark", "wine", "acidic", "full-bodied", NULL, "Kenya", "Africa", NULL, 0),
("Salt Lake Roasting Co", "Kenya Nyeri Barichu Gatomboya", "Light", "blackberry", "jasmine", "grapefruit", "sun-dried tomato", "Kenya", "Africa", NULL, 0),
("Salt Lake Roasting Co", "Late Night", "Light", "half decaf", NULL, NULL, NULL, NULL, NULL, NULL, 1),
("Salt Lake Roasting Co", "Mexico Decaf (Organic Swiss Water Process)", "Light", "snappy", "aromatic", NULL, NULL, "Mexico", "Central America", NULL, 1),
("Salt Lake Roasting Co", "Mexico Organic", "Light", "snappy", "dry", "aromatic", NULL, "Mexico", "Central America", NULL, 0),
("Salt Lake Roasting Co", "Mocha/Java KVW Decaf", "Dark", "full-bodied", "wild", "thick", NULL, "Indonesia", "Africa", "Java", 1),
("Salt Lake Roasting Co", "Mocha/Java", "Dark", "full-bodied", "wild", "thick", NULL, "Indonesia", "Java", "Africa", 0),
("Salt Lake Roasting Co", "Morning Thunder", "Medium", "elegant", "rich", "full-bodied", NULL, "Indonesia", "Sulawesi", NULL, 0),
("Salt Lake Roasting Co", "New Guinea", "Light", "clean", "bright", "rounded", NULL, "Indonesia", "Papua New Guinea", NULL, 0),
("Salt Lake Roasting Co", "Nicaragua (Organic & Fair Trade)", "Light", "clean", "lively", "refreshing", NULL, "Nicaragua", "Central America", NULL, 0),
("Salt Lake Roasting Co", "Old Dutch", "Dark", "earthy", "full-bodied", NULL, NULL, NULL, NULL, NULL, 0),
("Salt Lake Roasting Co", "Panama Maunier", "Light", "aromatic", "floral", "clean", "full-bodied", "Panama", "Central America", NULL, 0),
("Salt Lake Roasting Co", "Peru Norandino (Organic & Fair Trade)", "Light", "bright", "clean", NULL, NULL, "Peru", "South America", NULL, 0),
("Salt Lake Roasting Co", "Silverfork Blend", "Dark", "dark", "thick", NULL, NULL, NULL, NULL, NULL, 0),
("Salt Lake Roasting Co", "Sumatra", "Dark", "earthy", "chocolate", "syrup", NULL, "Indonesia", "Sumatra", NULL, 0),
("Salt Lake Roasting Co", "Sumatra (Organic)", "Dark", "earthy", "chocolate", "syrup", NULL, "Indonesia", "Sumatra", NULL, 0),
("Salt Lake Roasting Co", "Sumatra (Decaf)", "Dark", "earthy", "chocolate", "syrup", NULL, "Indonesia", "Sumatra", NULL, 1);

INSERT INTO coffee (brand, bean_name, roast, profile1, profile2, profile3, profile4, origin1, origin2, origin3, decaf)
VALUES ("Beans & Brew (High Altitude Roasting)", "House Blend", "Medium", "smooth", "full-bodied", "tangy", NULL, NULL, NULL, NULL, 0),
("Beans & Brew (High Altitude Roasting)", "Decaf House Blend", "Medium", "smooth", "full-bodied", "tangy", NULL, NULL, NULL, NULL, 1),
("Beans & Brew (High Altitude Roasting)", "Breakfast Blend", "Medium", "aromatic", "rich", "snappy", NULL, "Central America", "South America", NULL, 0),
("Beans & Brew (High Altitude Roasting)", "Colombia Santander Fair Trade Organic", "Dark", "full-bodied", "brown sugar", "lemon", "crisp", "Colombia", "Central America", NULL, 0),
("Beans & Brew (High Altitude Roasting)", "Espresso Fritalia", "Extra Dark", "intense", "dark", "rich", NULL, NULL, NULL, NULL, 0),
("Beans & Brew (High Altitude Roasting)", "French Roast", "Dark", "dark", "syrup", "rich", NULL, NULL, NULL, NULL, 0),
("Beans & Brew (High Altitude Roasting)", "French Roast Decaf", "Dark", "dark", "syrup", "rich", NULL, NULL, NULL, NULL, 1),
("Beans & Brew (High Altitude Roasting)", "French Roast Fair Trade Organic", "Dark", "dark", "syrup", "rich", NULL, "Sumatra", "Indonesia", "Central America", 0),
("Beans & Brew (High Altitude Roasting)", "Guatemala Huehuetenango Fair Trade Organic", "Medium", NULL, NULL, NULL, NULL, "Guatemala", "Central America", NULL, 0),
("Beans & Brew (High Altitude Roasting)", "Italian Roast", "Dark", "dark", "caramel", NULL, NULL, NULL, NULL, NULL, 0),
("Beans & Brew (High Altitude Roasting)", "Kenya Barichu Gatomboya", "Light", "grapefruit", "jasmine", "blackberry", "crisp", "Kenya", "Africa", NULL, 0),
("Beans & Brew (High Altitude Roasting)", "Rocky Mountain Blend", "Dark", "full-bodied", NULL, NULL, NULL, "Indonesia", NULL, NULL, 0),
("Beans & Brew (High Altitude Roasting)", "Sulawesi Jaya Peaberry", "Light", "full-bodied", NULL, NULL, NULL, "Sulawesi", "Indonesia", NULL, 0),
("Beans & Brew (High Altitude Roasting)", "Sumatra Mandheling", "Medium", "rich", "full-bodied", "smooth", NULL, "Sumatra", "Indonesia", NULL, 0),
("Beans & Brew (High Altitude Roasting)", "Wasatch Peaks Organic", "Medium", "rounded", NULL, NULL, NULL, NULL, NULL, NULL, 0);

INSERT INTO coffee (brand, bean_name, roast, profile1, profile2, profile3, profile4, origin1, origin2, origin3, decaf)
VALUES ("La Barba", "Colombia - Finca Filadelfia", "Light", "honey", "caramel", "dark chocolate", NULL, "Colombia", "Central America", NULL, 0),
("La Barba", "Colombia - Mujeres Cafeteras", "Medium", "caramel", "graham cracker", "milk chocolate", NULL, "Colombia", "Central America", NULL, 0),
("La Barba", "Colombia - Tolima Especial", "Light", "nougat", "red berry", "apricot", NULL, "Colombia", "Central America", NULL, 0),
("La Barba", "Peru - Rutas Del Inca", "Medium", "banana", "milk chocolate", "tropical", NULL, "Peru", "South America", NULL, 0),
("La Barba", "Ethiopia - Wotona Bultuma", "Light", "melon", "black tea", "floral", NULL, "Ethiopia", "Africa", NULL, 0),
("La Barba", "Guatemala - Manos de Mujer", "Light", "plum", "tangerine", "chocolate", NULL, "Guatemala", "Central America", NULL, 0),
("La Barba", "Anchor Blend", "Dark", "classic", "traditional", "smooth", NULL, "Colombia", "Brazil", "South America", 0),
("La Barba", "House Blend", "Medium", "dark chocolate", "smooth", "balanced", NULL, "Central America", "South America", NULL, 0),
("La Barba", "Hulihee - Espresso", "Dark", "almond", "toffee", "chocolate milk", NULL, "South America", "Central America", NULL, 0),
("La Barba", "La Barba Decaf - Swiss Water Process", "Medium", "smooth", "balanced", NULL, NULL, "Costa Rica", "Colombia", "Central America", 1),
("La Barba", "Kenya - Windrush AB", "Medium", NULL, NULL, NULL, NULL, "Kenya", "Africa", NULL, 0),
("La Barba", "Nicaragua -El Recreo Estate", "Dark", "cacao nibs", "almond", "tobacco", NULL, "Nicaragua", "Central America", NULL, 0);